Getting Started
---------------

This part of the docs focuses on describing what Centrifuge is, installation and running steps.

.. toctree::
   :maxdepth: 2

   starting/overview
   starting/install


Architecture and capabilities
-----------------------------

This part of the doc focuses on how Centrifuge built and features it provides.

.. toctree::
   :maxdepth: 2

   description/architecture


Configuration file
------------------

This part of the doc focuses on Centrifuge's configuration JSON file.

.. toctree::
   :maxdepth: 2

   configuration/description


Clients
-------

This part of the doc focuses on how clients work.

.. toctree::
   :maxdepth: 2

   clients/starting
   clients/writing
   clients/sending


Deployment
-----------

This part of the doc focuses on deploying Centrifuge in production environment.

.. toctree::
   :maxdepth: 2

   deployment/nginx
   deployment/supervisord


Extending
---------

This part of the doc focuses on ways to extend standard behaviour.

.. toctree::
   :maxdepth: 2

  	extending/backend
  	extending/callbacks


License, Contribution etc
-------------------------

Contribution notes and legal information are here (for those interested).

.. toctree::
   :maxdepth: 2

   marketing/license
   marketing/contribute
   marketing/author







