Getting Started
---------------

This part of the docs focuses on describing what Centrifuge is, installation and running steps.

.. toctree::
   :maxdepth: 2

   starting/overview
   starting/install


Architecture
------------

This part of the doc focuses on how Centrifuge built and features it provides.

.. toctree::
   :maxdepth: 1

   description/architecture


Configuration file
------------------

This part of the doc focuses on Centrifuge's configuration JSON file.

.. toctree::
   :maxdepth: 1

   configuration/description


Web interface
-------------

.. toctree::
   :maxdepth: 1

   web/overview
   web/login
   web/project_create
   web/project_settings


Cent
----

This part of the doc focuses on Cent - python tools to communicate with Centrifuge.

.. toctree::
   :maxdepth: 2

   cent/overview


Clients and events
------------------

This part of the doc focuses on how to communicate with Centrifuge from web browser.

.. toctree::
   :maxdepth: 2

   clients/starting
   clients/writing
   clients/sending


Deployment
-----------

This part of the doc focuses on deploying Centrifuge in production environment.

.. toctree::
   :maxdepth: 2

   deployment/nginx
   deployment/supervisord


License, Contribution etc
-------------------------

Contribution notes and legal information are here (for those interested).

.. toctree::
   :maxdepth: 2

   marketing/license
   marketing/contribute







